### PR TITLE
doc(build): continuous integration and delivery project setups

### PR DESCRIPTION
**Pull request by bcornett**

### CODE REVIEW

**Review by tulkjay — APPROVED** [review]

**Review by justinobney — COMMENTED** [review]
Is there an expected naming convention for this to work now?

**Comment by bcornett** [comment]
@justinobney If you want to use `$(Build.DefinitionName)` to keep your steps generic, then yes, the build definition needs to be named what your project is named. If not, then you can replace all the `$(Build.DefinitionName)`s with your project name.

**Comment by justinobney** [comment]
@bcornett move the code quality checks to correct position

**Comment by bcornett** [comment]
@justinobney - fixed code quality check position

**Review by justinobney — APPROVED** [review]
Looks good

**Pull request merged**
